Bill import
hiqdev/hipanel-module-finance pull request #227
Opened 2021-04-15 14:16 UTC by tafid

2021-04-16 07:44 UTC, strorch commented on src/actions/BillImportFromFileAction.php
> +        $session = Yii::$app->getSession();
в конструктор

2021-04-16 07:44 UTC, strorch commented on src/actions/BillImportFromFileAction.php
> +        if ($this->request->isPost) {
early return statement

2021-04-16 07:44 UTC, strorch commented on src/actions/BillImportFromFileAction.php
> +            $form->load($this->request->post());
if ($form->load() && $form->validate())

2021-04-16 07:44 UTC, strorch commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
я б це засунув в трай і кидав різні ексепшни, бо результат кетча редірект

2021-04-16 07:44 UTC, strorch commented on src/forms/BillImportFromFileForm.php
> +//            'deposit,dwgg_epayments',
видали пліз

2021-04-16 07:44 UTC, strorch commented on src/helpers/parser/BillsImporter.php
> +//            'deposit,dwgg_epayments' => ePaymentsParser::class,
коменти

2021-04-16 07:44 UTC, strorch commented on src/widgets/BillImportDropdownButton.php
> +        return sprintf(
а може винести це у в*юху?

2021-04-16 07:44 UTC, strorch commented on src/widgets/BillImportDropdownButton.php
> +            Modal::end();
а шо далі буде з цим модалом?

2021-04-16 07:44 UTC, strorch commented on src/helpers/parser/BillsImporter.php
> +            $bill->client_id = $clientsMap[$bill->client];
$clientsMap[$bill->client] завжди існуюьт?

2021-04-16 07:44 UTC, strorch commented on src/helpers/parser/BillsImporter.php
> +                if ($bill->client_id === $row['client_id'] && ((int)$bill->sum * 100) === $row['sum']) {
(int)$bill->sum * 100) отаке думаю краще переписать на маніпуляцію класом Money

2021-04-16 08:40 UTC, tafid commented on src/widgets/BillImportDropdownButton.php
> +        return sprintf(
не, не хочу

2021-04-16 08:42 UTC, tafid commented on src/forms/BillImportFromFileForm.php
> +//            'deposit,dwgg_epayments',
я на поиск правильных типов потратил 7 минут, по этому оставил в коментах, что бы второй раз опять это не делать

2021-04-16 08:42 UTC, tafid commented on src/helpers/parser/BillsImporter.php
> +//            'deposit,dwgg_epayments' => ePaymentsParser::class,
я на поиск правильных типов потратил 7 минут, по этому оставил в коментах, что бы второй раз опять это не делать

2021-04-16 09:15 UTC, tafid commented on src/widgets/BillImportDropdownButton.php
> +            Modal::end();
а что нужно?

2021-04-16 09:17 UTC, tafid commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
Можно конечно, но я не вижу существенной пользы. Если я ошибаюсь - расскажи

2021-04-16 09:29 UTC, strorch commented on src/widgets/BillImportDropdownButton.php
> +            Modal::end();
та просто питаю як ця штука з івента сработає, бо не поняв

2021-04-16 09:46 UTC, strorch commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
просто зараз дублюється 2 блока кода, які можна замінить на 

                try {
                    $bills = $this->parse($form);
                    if (empty($bills)) {
                         throw new NoParserApproiteType('message');
                    }
               catch (NoParserApproiteType $e) {
                 $session->setFlash('error', Yii::t('hipanel:finance', $e->getMessage()));
                 return $this->redirect();
                }

2021-04-16 09:47 UTC, strorch commented on src/forms/BillImportFromFileForm.php
> +//            'deposit,dwgg_epayments',
треба тоді доку написать)

2021-04-16 10:45 UTC, tafid commented on src/widgets/BillImportDropdownButton.php
> +            Modal::end();
На этот ивент никто не подписан, по этому она просто закроет див и буфер

2021-04-16 10:45 UTC, tafid commented on src/forms/BillImportFromFileForm.php
> +//            'deposit,dwgg_epayments',
не, тоже не нужно, это ищется один раз, сопоставляется и потом никто к этому не вернется. Короче - забей

2021-04-16 10:49 UTC, tafid commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
да, но для этого нужно сделать еще как минимум 1 файл. и это все нигде потом не переиспользуемо. По этому лучше лишних 3 строчки кода чем в файл + 6 строчек года, при чем это все применимо только тут и нигде больше

2021-04-16 11:59 UTC, strorch commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
а навіщо тут ще один файл?

2021-04-16 13:08 UTC, tafid commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
1 - empty($bills) это не ошибка а логика
2 - NoParserApproiteType - это не empty($bills)

2021-04-16 13:12 UTC, tafid commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
Ну или я вообще не понял твою задумку )

2021-04-16 13:17 UTC, tafid commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
Что бы объединить блок catch для всех вариантов, нужно сделать так:

`
 try {
                $bills = $this->parse($form);
                if (empty($bills)) {
                     throw new NoBillsException('message');
                }
           catch (\Exception $e) {
             $session->setFlash('error', Yii::t('hipanel:finance', $e->getMessage()));
             return $this->redirect();
            }
` 
вот я и говорю, что если сделать  так - нужно добавить еще и NoBillsException

2021-04-16 15:15 UTC, strorch commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
можна кинуть \RuntimeException і ніякий клас не треба, кетч піймає будь-який

2021-04-16 17:48 UTC, tafid commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
Тут согласен. Но empty($bill) это все же не ошибка и код на это как бы намекает )

2021-04-19 06:50 UTC, strorch commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
а якщо треба буде дописать іще блок бізнес логіки то треба буде писать іще один іф і ще раз записувать помилку і ще раз робить редірект?

2021-04-20 08:56 UTC, tafid commented on src/actions/BillImportFromFileAction.php
> +            if (empty($bills)) {
убедил, переделаю )

2021-04-20 09:13 UTC, strorch approved these changes

2021-04-21 08:21 UTC, hiqsol requested changes

2021-04-21 08:21 UTC, hiqsol commented on src/forms/BillImportFromFileForm.php
>              'deposit,dwgg_transferwise' => 'DataWeb Global Group BV - TransferWise',
не должны быть брендовые названия в этом коде
надо вынести в параметры или получать по апи

2021-04-22 10:43 UTC, tafid commented on src/forms/BillImportFromFileForm.php
>              'deposit,dwgg_transferwise' => 'DataWeb Global Group BV - TransferWise',
вынес

2021-04-22 15:23 UTC, hiqsol approved these changes

2021-05-11 11:40 UTC, merged