Mark
hiqdev/hipanel-module-finance pull request #235
Opened 2021-05-15 20:54 UTC by Drakorgaur

SalesCest

2021-05-16 17:15 UTC, hiqsol requested changes

2021-05-16 17:15 UTC, hiqsol commented on tests/acceptance/client/SalesCest.php
> +	$I->seeElement('input', ['name' => 'SaleSearch[object_type]']);
обрати внимание на отступы, мы используем 4 пробела, НЕ tab
```suggestion
        $I->seeElement('input', ['name' => 'SaleSearch[object_type]']);
```

2021-05-16 17:15 UTC, hiqsol commented on tests/acceptance/client/SalesCest.php
> +
лишние пустые строки не нужны
```suggestion
```

2021-05-16 17:15 UTC, hiqsol commented on tests/acceptance/client/SalesCest.php
> +class AccountSalesCest
вроде бы по логике других cest'ов этот должен называться просто `SaleCest`
```suggestion
class SaleCest
```

@SilverFire @strorch  ?

2021-05-20 10:40 UTC, strorch requested changes

2021-05-20 10:40 UTC, strorch commented on tests/acceptance/client/SalesCest.php
> + * @copyright Copyright (c) 2015-2019, HiQDev (http://hiqdev.com/)
```suggestion
 * @copyright Copyright (c) 2015-2021, HiQDev (http://hiqdev.com/)

```

2021-05-20 10:44 UTC, strorch approved these changes

2021-05-21 21:24 UTC, hiqsol approved these changes

2021-05-21 21:25 UTC, merged