Added toggle sign cest
hiqdev/hipanel-module-finance pull request #239
Opened 2021-05-21 09:25 UTC by Drakorgaur

Added ToggleSignCest.php
Edited Create.php 
Editted SalesCest.php - didn't work without login();

2021-05-21 21:14 UTC, hiqsol requested changes

2021-05-21 21:14 UTC, hiqsol commented on tests/_support/Page/bill/Create.php
> +        #(new Dropdown($I, $classSelector))->setValue($chargeData['class']);
закоменченый (мертвый) код стараемся не оставлять

2021-05-21 21:14 UTC, hiqsol commented on tests/_support/Page/bill/Create.php
> +    public function deleteBillById($BillId): void
сабжект PR'а не соответствует
похоже ты неумышленно затащил лишнее в этот PR
меняй или описание или изменения

2021-05-24 06:58 UTC, strorch requested changes
пр конфліктує з мастером

2021-05-24 06:58 UTC, strorch commented on tests/acceptance/client/ToggleSignCest.php
> +     *
лишня строка

2021-05-24 06:58 UTC, strorch commented on tests/acceptance/client/ToggleSignCest.php
> +        $I->see('$777.00');
це не треба хардкодить, треба брать з `provideDataCharge`

2021-05-24 06:58 UTC, strorch commented on tests/acceptance/client/ToggleSignCest.php
> +                'class' => 'Client',
масів треба вирівнять по `PSR`

2021-05-24 06:58 UTC, strorch commented on tests/acceptance/client/ToggleSignCest.php
> +            'client' => [ 'login' => 'hipanel_test_user',
масів треба вирівнять по `PSR`

2021-05-24 08:41 UTC, strorch requested changes

2021-05-24 08:41 UTC, strorch commented on tests/acceptance/client/ToggleSignCest.php
> +    private function ensureBillWasCreatedAndDeleteIt(Seller $I, $chargeData): void
```suggestion
    private function ensureBillWasCreatedAndDeleteIt(Seller $I, array $chargeData): void
```

2021-05-24 08:41 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +    public function deleteBillById($BillId): void
```suggestion
    public function deleteBillById($billId): void 
```

2021-05-24 08:41 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        $url = Url::to('@bill/view?id='. $BillId);
```suggestion
        $url = Url::to('@bill/view?id=' . $billId);
```

2021-05-24 08:41 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        $I->click('//a[@data-confirm="Are you sure you want to delete this item?"]');
```suggestion
        $I->click('Are you sure you want to delete this item?');
```

2021-05-24 08:41 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        $this->tester->click("//button[contains(text(),'Toggle sign')]");
```suggestion
        $this->tester->click('Toggle sign');
```

2021-05-24 11:34 UTC, strorch approved these changes

2021-05-24 12:57 UTC, merged