Added BillCopyCest and Modified Create
hiqdev/hipanel-module-finance pull request #246
Opened 2021-05-28 07:32 UTC by Drakorgaur

2021-06-01 10:15 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        $I->click('//a[@data-confirm="Are you sure you want to delete this item?"]');
не думаю що це треба

2021-06-01 10:21 UTC, strorch requested changes

2021-06-01 10:21 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        return $I->grabFromCurrentUrl('~id_in%5B0%5D=(\d+)~');
цей код повторюється, було б добре винести його і перевикористовувать

2021-06-01 10:21 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +        $dataBill = $this->provideDataBill();
оце треба в `Example` винести

2021-06-01 10:21 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +        $this->index = new IndexPage($I);
не використовується, можна видалить метод

2021-06-01 10:21 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +        $billId = $this->ensureICanCreateBillWithCharge($I, $dataBill['client']);
для створення біла з чарджом чи без треба використать 1 метод створення біла а не 2 різних

2021-06-01 10:21 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +        $this->ensurePreviousBillDidntChange($I, $billId, $dataBill['client']);
якийсь важкий тест з 3ма перевірками, тут або шось лишнє або треба роздилить на пару метод тестів

2021-06-01 11:52 UTC, Drakorgaur commented on tests/_support/Page/bill/Create.php
> +        $I->click('//a[@data-confirm="Are you sure you want to delete this item?"]');
К сожалению, надо. Помнишь, у меня раньше не работало заполнение _**class**_ в _**objectID**_? вот после того как мы переставили _local_ то оно почему-то заработало :/ а вот это перестало работать. Чудеса.

2021-06-01 11:59 UTC, Drakorgaur commented on tests/_support/Page/bill/Create.php
> +        return $I->grabFromCurrentUrl('~id_in%5B0%5D=(\d+)~');
Так он же в Create.php,  куда выносить?

2021-06-02 07:11 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        return $I->grabFromCurrentUrl('~id_in%5B0%5D=(\d+)~');
В Update.php :)

2021-06-02 07:12 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +    private $index;
це ж також можна видалить

2021-06-09 16:00 UTC, strorch requested changes

2021-06-09 16:00 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +    public function seeUpdateSuccess(): ?string
це не на сторінкі bill/create відбувається

2021-06-09 16:00 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +    private function ensureICanCreateBill(Seller $I, $billData): int
ти писав в якомусь пр-і метод який це саме робить, перевикористай

2021-06-09 16:00 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +     public function ensureICanCreateAndCopyBill(Seller $I, Example $example)
я думаю вистачить одного метода який створить і скопіює біл

2021-06-09 16:00 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +        $this->ensureBillWasCreatedCorrectly($I, $checkId, $example, $billSum);
це перевіряє інший тест, випіли

2021-06-09 16:00 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +        $this->ensureChargesWasCreatedCorrectly($I, $checkId, $example['charges']);
це перевіряє інший тест, випіли

2021-06-10 16:30 UTC, strorch requested changes

2021-06-10 16:30 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        $I->needPage(Url::to('@bill/copy?id=' . $billId));
це на сторінкі копіювання а не створення біла має буть

2021-06-10 16:30 UTC, strorch commented on tests/_support/Page/bill/Index.php
> +class Index extends Authenticated
```suggestion
class Index extends \hipanel\tests\_support\Page\IndexPage
```

2021-06-10 16:30 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +    public function ensureCopiedBillWithChargesWillBeCorrect(Seller $I, Example $example)
неправильна назва: ти тут створюєш біл і копіюєш його. ти можеш в проперті класа зберегти айдішнік після теста і його перевикористать в цьому, [наприклад](https://github.com/hiqdev/hipanel-module-stock/blob/master/tests/acceptance/manager/OrdersCest.php#L54).

який взагалі ти кейс перевіряєш?

2021-06-11 09:59 UTC, Drakorgaur commented on tests/acceptance/seller/BillCopyCest.php
> +    public function ensureCopiedBillWithChargesWillBeCorrect(Seller $I, Example $example)
кейс - данные с чарджей не пропадут

2021-06-11 12:43 UTC, strorch requested changes

2021-06-11 12:43 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +        $billId = --$this->copyId;
шта?)

2021-06-11 12:43 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +    private function ensurePreviousBillDidntChange(Seller $I, $id, $dataBill): void
$id можна покласти в $dataBill ше й тайпхінта немає

2021-06-11 12:43 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +        $indexPage = new IndexPage($I);
поклади це в `_before`

2021-06-11 12:43 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        $copyPage = new Copy($I);
винеси цю логіку в тест, бо сторінка створення за сторінку копіювання не відповідає

2021-06-11 12:43 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +    private $create;
```suggestion
    private Create $create;
```

а комент удали

2021-06-11 12:43 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +    /**
```suggestion

    /**
```

2021-06-11 12:43 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +    private function grabBillIdFromUrl()
тайпхінт

2021-06-11 12:43 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +    public function createAndCopyBill($billData)
тайпхінт

2021-06-11 12:43 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +    public function getChargesAmount()
тайпхінт

2021-06-11 12:43 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +    public function _before(Seller $I)
тайпхінт

2021-06-11 12:43 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +     public function ensureICanCreateAndCopyBillWithoutCharges(Seller $I, Example $example)
тайпхінт

2021-06-11 12:43 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +    public function createAndCopyBillWithCharges(Seller $I, Example $example)
тайпхінт

2021-06-11 12:43 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +    public function ensureCopiedBillWithChargesIsCorrect(Seller $I, Example $example)
тайпхінт

2021-06-14 08:42 UTC, Drakorgaur commented on tests/acceptance/seller/BillCopyCest.php
> +    public function createAndCopyBillWithCharges(Seller $I, Example $example)
что тут?

2021-06-14 08:42 UTC, Drakorgaur commented on tests/acceptance/seller/BillCopyCest.php
> +    public function ensureCopiedBillWithChargesIsCorrect(Seller $I, Example $example)
и тут

2021-06-14 08:43 UTC, Drakorgaur commented on tests/acceptance/seller/BillCopyCest.php
> +     public function ensureICanCreateAndCopyBillWithoutCharges(Seller $I, Example $example)
и тут что?)

2021-06-14 11:19 UTC, strorch requested changes

2021-06-14 11:19 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +    public function createBill($billData): ?string
цей метод не потрібний, роби як в інших тестах

2021-06-14 11:19 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        return $id;
просто 

        return $this->grabBillIdFromUrl();

2021-06-14 11:19 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        $I->click('//a[@data-confirm="Are you sure you want to delete this item?"]');
переробиш, в лічкі обсудили

2021-06-14 11:19 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +    public function getAndSetBillTotalSum(): int
цей метод ситуативний для теста, перенеси цей код в нього

2021-06-14 11:19 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +    public function createBill($billData): ?string
або хай цей метод буде, але в інших тестах його використай, щоб усі біли в усих тестах однаково створювались

2021-06-14 11:19 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +     public function ensureICanCreateAndCopyBillWithoutCharges(Seller $I, Example $example): void
не правильна назва теста

2021-06-14 11:19 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +
```suggestion
```

2021-06-14 14:30 UTC, strorch commented
також треба пофіксить конфлікт

2021-06-15 08:28 UTC, strorch requested changes

2021-06-15 08:28 UTC, strorch commented on tests/_support/Page/bill/Copy.php
> +    public function copyBill($billId): void
тайпхінт

2021-06-15 08:28 UTC, strorch commented on tests/_support/Page/bill/Index.php
> +        return $id;
просто 

      return $this->grabBillIdFromUrl();

2021-06-15 08:28 UTC, strorch commented on tests/acceptance/seller/BillCopyCest.php
> +    private function createBill(Seller $I, $billData): ?string
тайпхінт

2021-06-15 08:43 UTC, strorch approved these changes

2021-06-15 08:43 UTC, merged