Purse initial
hiqdev/hipanel-module-finance pull request #247
Opened 2021-05-31 07:47 UTC by bladeroot

2021-06-01 08:37 UTC, strorch requested changes

2021-06-01 08:37 UTC, strorch commented on src/forms/BillImportForm.php
> +        if (count($chunks) !== 7) {
```suggestion
        if (count($chunks) !== self::SHO_CE_ZA_CONSTANTA) {
```

2021-06-01 08:37 UTC, strorch commented on src/grid/PurseRepresentations.php
> + * @copyright Copyright (c) 2015-2019, HiQDev (http://hiqdev.com/)
видали цей комент, ще й дати просрочені

2021-06-01 08:37 UTC, strorch commented on src/models/PurseSearch.php
> + * @copyright Copyright (c) 2015-2019, HiQDev (http://hiqdev.com/)
і цей

2021-06-01 08:37 UTC, strorch commented on src/views/purse/index.php
> +                \n
а хіба це хтмл формат?

2021-06-01 08:37 UTC, strorch commented on src/widgets/combo/ResellerRequisitesCombo.php
> +                    return markup; // Allows HTML
а чого так можна

2021-06-01 08:37 UTC, strorch commented on src/views/purse/index.php
> +                 Yii::$app->user->can('support') ? 'seller' : null
от такого позбавляємось в коді

2021-06-01 08:37 UTC, strorch commented on src/views/purse/_search.php
> +<?php if (Yii::$app->user->can('support')) : ?>
от такого позбавляємось в коді

2021-06-01 08:37 UTC, strorch commented on src/forms/BillImportForm.php
> +    protected function getClients($logins)
return type, private function type

2021-06-01 08:37 UTC, strorch commented on src/forms/BillImportForm.php
> +    protected function convertRequisiteNameToId(string $requisite, string $client)
return type, private function type

2021-06-01 08:37 UTC, strorch commented on src/forms/BillImportForm.php
> +    protected function getRequisites(string $seller)
return type, private function type

2021-06-01 08:42 UTC, hiqsol commented on src/forms/BillImportForm.php
> +        if (count($chunks) !== 7) {
:+1:

2021-06-01 08:44 UTC, hiqsol commented on src/forms/BillImportForm.php
> +                $bill->setAttributes(compact('client', 'time', 'sum', 'currency', 'type', 'label', 'quantity', 'requisite'));
Юра! ... Ну сколько можно?!
ПР про пурсы, а тут - хyzk-маяк - реквизиты в импорте платежей.

2021-06-01 08:46 UTC, hiqsol commented on src/views/purse/index.php
> +                 Yii::$app->user->can('support') ? 'seller' : null
да, тут `access-subclients`

2021-06-01 10:23 UTC, bladeroot commented on src/forms/BillImportForm.php
> +        if (count($chunks) !== 7) {
А спитайте Ви у того, хто це робив із самого початку. Я то зрозумів що це. Хотете винести в константу - ок.

2021-06-01 10:25 UTC, bladeroot commented on src/views/purse/index.php
> +                \n
Copy+Past. Я напишу, звыдки копіював

2021-06-01 10:26 UTC, bladeroot commented on src/widgets/combo/ResellerRequisitesCombo.php
> +                    return markup; // Allows HTML
Copy+Past, але поверх (без дублювання коду) воно не прцю'

2021-06-01 10:28 UTC, bladeroot commented on src/views/purse/_search.php
> +<?php if (Yii::$app->user->can('support')) : ?>
Хто буде вести новіґстарі права, роздавати їх? Я свого часу пропонував на кожен єкшн завести право. Сказали не треба. Тепер - із правами будь ласка в ідс, користуюсь чим є

2021-06-01 10:29 UTC, bladeroot commented on src/forms/BillImportForm.php
> +                $bill->setAttributes(compact('client', 'time', 'sum', 'currency', 'type', 'label', 'quantity', 'requisite'));
Сорри, тут сразу 2 задачи. =(((

2021-06-01 10:33 UTC, bladeroot commented on src/views/purse/index.php
> +                 Yii::$app->user->can('support') ? 'seller' : null
access-reseller ну по моему

2021-06-01 10:36 UTC, bladeroot commented on src/forms/BillImportForm.php
> +    protected function getClients($logins)
Не хочу я використовувати прайват! Якщо захочу, щов використовувалось "як є" напишу файнал. Протектед. Кому треба, сам перепише у свому класі

2021-06-05 07:29 UTC, strorch approved these changes

2021-06-06 09:21 UTC, hiqsol commented on src/views/purse/_search.php
> +<?php if (Yii::$app->user->can('support')) : ?>
```suggestion
<?php if (Yii::$app->user->can('access-subclients')) : ?>
```

2021-06-06 09:23 UTC, hiqsol commented on src/views/purse/index.php
> +                 Yii::$app->user->can('support') ? 'seller' : null
```suggestion
                 Yii::$app->user->can('access-subclients') ? 'client' : null,
                 Yii::$app->user->can('access-subclients') ? 'seller' : null
```

2021-06-06 09:30 UTC, hiqsol requested changes

2021-06-06 09:30 UTC, hiqsol commented on src/widgets/combo/ResellerRequisitesCombo.php
> +                    return markup; // Allows HTML
name и organization надо защищать от XSS
Макс правильно спрашивает - где эскейпится?

2021-06-07 06:54 UTC, bladeroot commented on src/widgets/combo/ResellerRequisitesCombo.php
> +                    return markup; // Allows HTML
Ну на сколько я знаю, еще в гриде вывода реквизита\контакта.

2021-06-07 08:03 UTC, hiqsol commented on src/views/purse/_search.php
> +<?php if (Yii::$app->user->can('support')) : ?>
вместо support - access-subclients в большинстве случаев подходит

2021-06-07 08:04 UTC, hiqsol commented on src/widgets/combo/ResellerRequisitesCombo.php
> +                    return markup; // Allows HTML
"ну на сколько я знаю" - совершенно недостаточно, покажи код

2021-06-07 14:02 UTC, hiqsol commented on src/widgets/combo/RequisitesCombo.php
> +                    return '<b>' + (data.name).replace(/(<([^>]+)>)/ig,'') + '</b><br>' + (data.organization).replace(/(<([^>]+)>)/ig,'');
```suggestion
                    var name = data.name.replace(/(<([^>]+)>)/ig,'');
                    var organization = data.organization.replace(/(<([^>]+)>)/ig,'');
                    return '<b>' + name + '</b><br>' + organization;
```

уделяй внимание читаемости

2021-06-08 06:48 UTC, strorch requested changes

2021-06-08 06:48 UTC, strorch commented on src/forms/BillImportForm.php
> +                    list($client, $time, $sum, $currency, $type, $label) = $splitted;
```suggestion
                    [$client, $time, $sum, $currency, $type, $label] = $splitted;
```

2021-06-08 06:48 UTC, strorch commented on src/forms/BillImportForm.php
> +                    list($client, $time, $sum, $currency, $type, $label, $requisite) = $splitted;
```suggestion
                    [$client, $time, $sum, $currency, $type, $label, $requisite] = $splitted;
```

2021-06-11 09:06 UTC, SilverFire requested changes

2021-06-11 09:06 UTC, SilverFire commented on src/widgets/combo/RequisitesCombo.php
> +                    var name = data.name.replace(/(<([^>]+)>)/ig,'');
Самописные попытки защиты от XSS обычно дырявые.
https://jsfiddle.net/uj80dom2/1/

2021-06-11 09:06 UTC, SilverFire commented on src/widgets/combo/ResellerRequisitesCombo.php
> +                    var name = data.name.replace(/(<([^>]+)>)/ig,'');
Самописные попытки защиты от XSS обычно дырявые.
https://jsfiddle.net/uj80dom2/1/

2021-06-11 09:08 UTC, hiqsol commented on src/widgets/combo/ResellerRequisitesCombo.php
> +                    var name = data.name.replace(/(<([^>]+)>)/ig,'');
:+1:

2021-06-14 14:27 UTC, strorch requested changes

2021-06-14 14:27 UTC, strorch commented on src/forms/BillImportForm.php
> +                $quantity = 1;
```suggestion
                $quantity = self::DEFAULT_QUANTITY;
```

2021-06-14 14:27 UTC, strorch commented on src/views/purse/_form.php
> +                            <h3 class="box-title"><?= $model->client ?> <?= $model->currency ?></h3>
```suggestion
                            <h3 class="box-title"><?= Html::encode($model->client) ?> <?= Html::encode($model->currency) ?></h3>
```

2021-06-16 09:40 UTC, SilverFire approved these changes

2021-06-16 09:40 UTC, merged