Added TarrifPlanTip, Edited Create and Update for plan
hiqdev/hipanel-module-finance pull request #248
Opened 2021-05-31 07:51 UTC by Drakorgaur

2021-06-01 08:38 UTC, hiqsol requested changes

2021-06-01 08:38 UTC, hiqsol commented on tests/acceptance/seller/TariffPlansTipCest.php
> +    protected function getCurrnecyfData(): array
тут столько typos, что даже неясно что имелось в виду

2021-06-01 09:36 UTC, Drakorgaur commented on tests/acceptance/seller/TariffPlansTipCest.php
> +    protected function getCurrnecyfData(): array
А что кроме Currency и тавтологии createCreateSharedPrice?

2021-06-01 10:14 UTC, strorch requested changes

2021-06-01 10:14 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +    protected function getPriceData(): array
данні з цього методу краще перенеси  в  `getTariffData`

2021-06-01 10:14 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +            'usd' => 'USD',
cписок валют повторюється багато де, наприклад [тут](https://github.com/hiqdev/hipanel-module-finance/blob/master/tests/_support/Page/plan/Create.php#L134-L135)

пропоную винести це в якусь константу або в парамси або діставать запитом в апі

2021-06-01 10:14 UTC, strorch commented on tests/_support/Page/plan/Create.php
> -        $this->fillName();
мені здається ці зміни можуть поламать тести існуючі тести, навіщо ти це видаляв?

2021-06-02 07:10 UTC, Drakorgaur commented on tests/acceptance/seller/TariffPlansTipCest.php
> +            'usd' => 'USD',
Я и поиск нашли список ток там, позаменял на метод.

2021-06-05 10:51 UTC, strorch commented on tests/_support/Page/plan/Create.php
> -        $this->fillName();
короче, є ще тести до яких в тебе немає доступа і вони так не пройдуть. не пройдуть по причинам зворотної сумісності. нові фічі це окей або рефакторить приватні методи. але якщо міняється логіка то треба все перевірить. в цьому випадку ти порушив сігнатуру публічного метода і видалив функціонал що він робить, так шо треба вернуть назад усе і нові тести писать з використанням того шо є

2021-06-14 09:53 UTC, strorch requested changes

2021-06-14 09:53 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +        $I->click("//button[contains(text(), 'Proceed to creation')]");
перевикористовуй код!!!

https://github.com/hiqdev/hipanel-module-finance/blob/386d1fef18d630da6b43141b63bc969fe101604c/tests/_support/Page/price/Create.php#L72-L72

2021-06-14 09:53 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +        $I->click("//a[contains(text(), 'Create price')]");
це ж уже все є!!!

https://github.com/hiqdev/hipanel-module-finance/blob/386d1fef18d630da6b43141b63bc969fe101604c/tests/_support/Page/price/Create.php#L44-L44

2021-06-14 09:53 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +        $I->click("//a[contains(text(), 'Create price')]");
да згоден може лежить не в логічному місці, треба перенести

2021-06-14 09:53 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +        (new Dropdown($this->tester, "//select[@id='plan-type']"))
!!!!

https://github.com/hiqdev/hipanel-module-finance/blob/386d1fef18d630da6b43141b63bc969fe101604c/tests/_support/Page/plan/Create.php#L60-L60

2021-06-14 09:53 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +        (new Select2($this->tester, '#plan-currency'))
https://github.com/hiqdev/hipanel-module-finance/blob/386d1fef18d630da6b43141b63bc969fe101604c/tests/_support/Page/plan/Create.php#L80-L80

2021-06-14 09:53 UTC, strorch commented on tests/_support/Page/plan/Create.php
> -            'pln' => 'PLN',
а чого це випілив

2021-06-14 09:53 UTC, strorch commented on tests/_support/Page/plan/Update.php
> +    public function updatePlanWithNewCurrency($currency, $id): void
не думаю що це треба в окремий метод виносить, можна просто в тесті заюзать код який заповнює інпути

2021-06-14 09:53 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +    public function ensureIndexPageWorks(Seller $I,  Example $example): void
неправильна назва теста

2021-06-14 09:53 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +    private function ensureTipsAreCorrect(Seller $I, $id, $priceData): void
1. тайпхінт
2. шо робить цей метод? тут всі валюти тестяться і ше шось це назві не відповідає

2021-06-16 10:42 UTC, strorch requested changes

2021-06-16 10:42 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +        $pricePage = new PriceCreate($I, 0);
ето чьо?)

2021-06-16 10:42 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +        $planPage = new PlanCreate($I);
не використовується

2021-06-16 10:42 UTC, strorch commented on tests/_support/Page/plan/Update.php
> +use hipanel\tests\_support\Page\Widget\Input\Select2;
це лишне

2021-06-16 10:42 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +        foreach ($list as $key => $text) {
```suggestion
        foreach ($this->getCurrencyList() as $key => $text) {
```

2021-06-16 10:42 UTC, strorch commented on tests/_support/Page/price/Create.php
> +        $I->click("//li/a[contains(text(), 'Create shared price')]");
ти писав вроді хелпер який це заміняє

2021-06-16 10:42 UTC, strorch commented on tests/_support/Page/price/Create.php
> +        $I->click("//li/a[contains(text(), 'Create shared price')]");
https://github.com/hiqdev/hipanel-module-finance/blob/1c22c82e639e546e2dc7e6af6376ae77c563791f/tests/_support/Page/price/Create.php#L40

заюзай цей метод

2021-06-16 10:42 UTC, strorch commented on tests/_support/Page/price/Create.php
> +        $I->click("//li/a[contains(text(), 'Create shared price')]");
цей метод взагалі лишній можна просто в тесті юзнуть заповнення цих полів

2021-06-16 10:42 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +    private function ensureTipsAreCorrect(Seller $I, string $id, array $priceData): void
якіто странні аргументи, чого айді не в прайс дата? шо це за айді

2021-06-17 07:14 UTC, strorch requested changes

2021-06-17 07:14 UTC, strorch commented on tests/_support/Page/price/Create.php
> +        $viewPage = new View($I, $id);
уже який раз одне і те саме.. шо клас вью робить в класі креайт????

2021-06-17 07:14 UTC, strorch commented on tests/_support/Page/price/Create.php
> +    public function createRandomPrices(string $objectName, string $templateName, string $priceType, string $id): void
навіщо класу креайт якась айдішка??? він же створює це айді

2021-06-17 07:14 UTC, strorch commented on tests/_support/Page/price/Create.php
> +            ->setValue($templateName);
навіщо цей фікс

2021-06-17 07:14 UTC, strorch commented on tests/_support/Page/price/Create.php
> +
```suggestion
```

2021-06-17 07:14 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +        $currency = $planPage->getCurrencyList();
зроби трейт tests/_support/Helper/CurrencyListTrait і включи його в PriceCreate і PlanCreate, щоб перевикористать код, а не викликать план пейдж для цього

2021-06-17 08:50 UTC, Drakorgaur commented on tests/acceptance/seller/TariffPlansTipCest.php
> +        $planPage = new PlanCreate($I);
а как надо?

2021-06-17 10:22 UTC, Drakorgaur commented on tests/_support/Page/plan/Create.php
> +            'template' => 'Template tariff',
Почему удалил:
Нет старых типов вообще.

2021-06-17 10:23 UTC, Drakorgaur commented on tests/_support/Page/plan/Create.php
> +            'template' => 'Template tariff',
Я пускал проверочный тест, что трейт работает как надо. Вот обнаружил, что тест ругается

2021-06-17 10:24 UTC, Drakorgaur commented on tests/_support/Page/price/Create.php
> +        $this->tester->click("//span[@id='select2-template_plan_id-container']");
Тут была проблема в том, что Select2 пытался заполнить пол, которое появляется после клика на Select2.
Проделывает все как юзер, говоришь))

2021-06-17 10:43 UTC, strorch requested changes

2021-06-17 10:43 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +        foreach($currency as $key => $currentCurrency)
```suggestion
        foreach($this->getCurrencyList() as $key => $currentCurrency)
```

2021-06-17 10:43 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +    use CurrencyListTrait;
```suggestion
    use CurrencyListTrait;

```

2021-06-17 10:43 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +    use CurrencyListTrait;
```suggestion
    use CurrencyListTrait;

```

2021-06-17 10:43 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +use hipanel\tests\_support\Helper\CurrencyListTrait;
сорі додай цей трейт в цей пр

```suggestion
use hipanel\module\finance\tests\_support\Helper\CurrencyListTrait;
```

2021-06-17 10:43 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +            'template' => 'Template tariff',
🤔
короче це треба глобально пофіксить, щоб цей список задавався в тесті, бо він плаває для різних сетапів панелі

2021-06-23 07:24 UTC, strorch requested changes

2021-06-23 07:24 UTC, strorch commented on tests/_support/Helper/CurrencyListTrait.php
> +trait CurrencyListTrait {
PSR!!

2021-06-23 07:24 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +    use CurrencyListTrait;
кстаті, я мав на увазі включить цей трейт в клас `PriceCreate` бо виходить, що в тебе його юзає клас типу пейдж і клас тесту.

2021-06-23 07:24 UTC, strorch commented on tests/_support/Page/price/Create.php
> +    {
тайпхінт

2021-06-23 08:09 UTC, strorch requested changes

2021-06-23 08:09 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +    use CurrencyListTrait;
видали трейт з теста

2021-06-23 08:09 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +            $I->click("div[class*='0'] button[class*='formula-help']");
бачиш, тест став трохи не читабельним. що треба зробить - це getCurrencyList юзать з PriceCreate, і все що ти робиш в циклі винести в який-то метод в PriceCreate

2021-06-23 08:09 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +        {
не PSR!!!

2021-06-23 08:09 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +            'tariff' => [
лишня вложеность

2021-06-23 08:10 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +            'template' => 'Template tariff',
зроби так, щоб цей список брався не з змінної як тут, а з дата провайдера теста. це поламає старий тест, але я його пофікшу.

2021-06-23 09:21 UTC, Drakorgaur commented on tests/acceptance/seller/TariffPlansTipCest.php
> +            'tariff' => [
![image](https://user-images.githubusercontent.com/83531949/123071604-78c13480-d41d-11eb-9fba-e78c2619fcf0.png)
у меня в массиве под тарифом есть как план так и прайс. Если без этого экзампл сожрет их, и я не смогу разделять их данные

2021-06-23 09:38 UTC, strorch approved these changes

2021-06-23 09:38 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +    public function seeFields(array $list): void
```suggestion
    public function seeFields(array $typeDropDownElements): void
```

2021-06-23 09:38 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +        $this->seeTypeDropdownList($list);
```suggestion
        $this->seeTypeDropdownList($typeDropDownElements);
```

2021-06-23 09:41 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +        $this->seeTypeDropdownList($typeDropDownElements);
я переіменував змінні, але так не годиться. всі тестові дані приходять в цей клас через конструктор, тобі треба їх запихнуть також туда. hipanel\modules\finance\tests\_support\Page\plan\Plan додай свойство protected  array $typeDropDownElements

2021-06-23 10:17 UTC, strorch requested changes

2021-06-23 10:17 UTC, strorch commented on tests/_support/Page/plan/Create.php
> +        $this->seeTypeDropdownList($this->typeDropDownElements);
цього не треба робить

2021-06-23 10:17 UTC, strorch commented on tests/_support/Page/plan/Create.php
>          foreach ($list as $key => $text) {
отут можеш звернутись до проперті

2021-06-23 10:17 UTC, strorch commented on tests/_support/Page/plan/Plan.php
> +    public function __construct(AcceptanceTester $I, $fields = null, $typeDropDownElements = null)
не, поклади це в філдс і забери з філдс

2021-06-25 07:34 UTC, strorch commented on tests/_support/Page/price/View.php
> +    protected function getId(): ?string
```suggestion
    public function getId(): ?string
```

2021-06-25 07:36 UTC, strorch approved these changes

2021-06-25 07:40 UTC, merged