Added ChargeSumMatchBillSum
hiqdev/hipanel-module-finance pull request #249
Opened 2021-05-31 09:04 UTC by Drakorgaur

2021-06-01 08:33 UTC, hiqsol approved these changes

2021-06-01 09:59 UTC, strorch requested changes

2021-06-01 09:59 UTC, strorch commented on tests/acceptance/seller/ChargeSumMatchBillSumCest.php
> +        $I->cantSee('Bill sum must match charges sum: -762.7');
```suggestion
        $I->cantSee('Bill sum must match charges sum: -' . $example['sum']);
```

2021-06-01 09:59 UTC, strorch commented on tests/acceptance/seller/ChargeSumMatchBillSumCest.php
> +}
```suggestion
}

```

2021-06-02 09:50 UTC, strorch commented on tests/acceptance/seller/ChargeSumMatchBillSumCest.php
> +        $page->addCharge($example['charge1']);
перероби пліз отак

```suggestion
        $exampleArray = iterator_to_array($example->getIterator());
        $page->addCharges($exampleArray['charges']);
```

2021-06-05 09:01 UTC, strorch commented on tests/acceptance/seller/ChargeSumMatchBillSumCest.php
> +        $exampleArray = iterator_to_array($example->getIterator());
в лічкі обсудили

2021-06-07 09:21 UTC, Drakorgaur commented on tests/acceptance/seller/ChargeSumMatchBillSumCest.php
> +        $exampleArray = iterator_to_array($example->getIterator());
По поводу одним методом добавлять и билл, и чардж если тот присутсвуте? <- это добавил, если ты про что-то другое, уточни плез :c

2021-06-10 16:14 UTC, strorch requested changes

2021-06-10 16:14 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +                $this->addCharge($charge);
в лічкі обсудили

2021-06-14 10:25 UTC, closed without merging