Added AddingChargesCest and updated Create
hiqdev/hipanel-module-finance pull request #252
Opened 2021-06-01 11:49 UTC by Drakorgaur

2021-06-01 12:01 UTC, strorch requested changes

2021-06-01 12:01 UTC, strorch commented on tests/acceptance/seller/AddingChargesCest.php
> +        $page = new Create($I);
```suggestion
        $createPage = new Create($I);
```

2021-06-09 16:01 UTC, strorch requested changes

2021-06-09 16:01 UTC, strorch commented on tests/acceptance/seller/AddingChargesCest.php
> +        $viewData['charge1'] = $update->addChargeInBillById($billId, $example['charge1']);
обсудили в лічькі

2021-06-11 12:52 UTC, strorch requested changes

2021-06-11 12:52 UTC, strorch commented on tests/_support/Page/bill/Update.php
> +    public function addChargeInBillById($billId, array $charge): array
оцей метод в пулреквесті не використовується + тайпхінт

2021-06-11 12:52 UTC, strorch commented on tests/_support/Page/bill/Update.php
> +    public function openBillUpdateById($billId): void
тайпхінт

2021-06-11 12:52 UTC, strorch commented on tests/_support/Page/bill/View.php
> +    public function viewBillById($billId): void
тайпхінт

2021-06-11 12:52 UTC, strorch commented on tests/acceptance/seller/AddingChargesCest.php
> +
```suggestion
```

2021-06-14 10:37 UTC, strorch commented on tests/_support/Page/bill/View.php
> +                $this->tester->see($billData, '//div[@class="table-responsive"]//tr');
```suggestion
            $this->tester->see($billData, '//div[@class="table-responsive"]//tr');
```

2021-06-14 14:15 UTC, strorch requested changes

2021-06-15 11:10 UTC, Drakorgaur commented on tests/_support/Page/bill/View.php
> +    public function ensureChargeViewContainsData(array $chargeData): void
Я подумал, что раз это на страничке View, то пусть через нее делает. Или лучше убрать посредника и сразу обращатсья к grid'y?

2021-06-15 11:12 UTC, strorch commented on tests/_support/Page/bill/View.php
> +    public function ensureChargeViewContainsData(array $chargeData): void
ну ти ж можеш звертатись до гріда на сторінкі вью?)

2021-06-15 11:14 UTC, Drakorgaur commented on tests/_support/Page/bill/View.php
> +    public function ensureChargeViewContainsData(array $chargeData): void
так оставляю?

2021-06-15 11:21 UTC, strorch requested changes

2021-06-15 11:21 UTC, strorch commented on tests/_support/Page/bill/View.php
> +        $indexPage->gridView->ChargeViewContainsData($billData);
```suggestion
        $indexPage->gridView->сontainsDataWHERE($billData);
```
грід вью нічо не має знать про то на якій він сторінці

2021-06-15 11:21 UTC, strorch commented on tests/_support/Page/bill/View.php
> +        $indexPage->gridView->BillViewContainsData($billData);
грід вью нічо не має знать про то на якій він сторінці
```suggestion
        $indexPage->gridView->containsDataWHERE($billData);
```

2021-06-15 11:23 UTC, strorch requested changes

2021-06-15 11:23 UTC, strorch commented on tests/_support/Page/bill/View.php
> +        $indexPage = new IndexPage($I);
стоямба, це має буть грід як проперті до класа View

2021-06-15 11:23 UTC, strorch commented on tests/_support/Page/bill/View.php
> +class View extends Create
чого сторінка в*ю наслідується від креайт

2021-06-15 12:48 UTC, strorch commented on tests/_support/Page/bill/View.php
> +        $gridView = new Grid($I);
в конструктор

2021-06-15 15:05 UTC, strorch approved these changes

2021-06-15 15:05 UTC, strorch commented on tests/_support/Page/bill/View.php
> +    public function __construct(AcceptanceTester $I, string $gridSelector = null)
```suggestion
    public function __construct(AcceptanceTester $I)
```

2021-06-15 15:05 UTC, strorch commented on tests/_support/Page/bill/View.php
> +        $this->gridView = new Grid($I, $gridSelector ?? $this->gridSelector);
```suggestion
        $this->gridView = new Grid($I, $this->gridSelector);
```

2021-06-15 15:07 UTC, merged