Internal transfer update
hiqdev/hipanel-module-finance pull request #267
Opened 2021-06-24 09:29 UTC by Drakorgaur

Чутка перегружен, к тому же еще Грид пришлось обновлять. Но тип имхо просто вливать в билл млрд и надеяться, что у аккаунта баланс негативный меньше чем на миллиард хуже.

2021-06-25 07:50 UTC, strorch requested changes
напиши про шо ці правки бо я кодстайл чекнув а суть не улавлюю

2021-06-25 07:50 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        $this->indexPage = new IndexPage($I);
зроби шоб Index наслідувався від IndexPage ато странний дубль який то

2021-06-25 07:50 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +                    'client'     => 'hipanel_test_user1',
а оце нашо

2021-06-25 07:50 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        if(similar_text($currentBalance, '-')) {
pSR!!!!!!!!!!

2021-06-25 07:50 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        if(similar_text($currentBalance, '-')) {
блін якто сложно написано, почитай про early return statement

2021-06-25 07:50 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +            $billInfo['bill']['charges']['charge2'] = $billInfo['bill']['charges']['charge1'];
wtf charge2

2021-06-25 07:50 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +            $billInfo['bill']['charges']['charge2'] = $billInfo['bill']['charges']['charge1'];
для красоти можеш просто зробить
 
      $billInfo['bill']['charges']['charge2'] = [
           ...
      ];

2021-06-25 09:12 UTC, Drakorgaur commented on tests/acceptance/seller/InternalTransferCest.php
> +                    'client'     => 'hipanel_test_user1',
хз, для удобства, могу переназначить назад на просто hipanel_test_user
hipanel_test_user1 -> hipanel_test_user2

2021-06-25 09:20 UTC, Drakorgaur commented
Суть правок и charge 2:
Пред версия тетса добавляла 1000 через bill, и снимала 1000 через трансфер.
Но не учитывала, что на аккаунте уже может быть отрицательный баланс. Так что суть charge2 - добавить в билл при полполнении на 1000 для трансфера[это charge1]
сумму отрицательного баланса(чтоб тот вышел в ноль)[charge2]

2021-06-25 09:31 UTC, Drakorgaur commented on tests/acceptance/seller/InternalTransferCest.php
> +            $billInfo['bill']['charges']['charge2'] = $billInfo['bill']['charges']['charge1'];
по-моему такое се...
если делать так:

```
$billInfo['bill']['charges']['charge2'] = [
                'type' => 'Paypal',
                'sum'  => ++$sum,
            ];
```
то оно ж перезапишет objectId, Class и бла-бла на null

а если

```
$billInfo['bill']['charges']['charge2'] = [
                'class' => $billInfo['bill']['charges']['charge1']['class']
                'objectId' => $billInfo['bill']['charges']['charge1']['objectId']
                'type' => 'Paypal',
                'sum'  => ++$sum,
            ];
```
это выглядит менее красиво...

2021-06-29 07:36 UTC, strorch requested changes

2021-06-29 07:36 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +            $billInfo['bill']['charges']['charge2'] = $billInfo['bill']['charges']['charge1'];
я по коду не бачу, де перед цим в тесті в цей масів кладуться якісь айдішніки... в дата провайдері тільки charge1 є.

2021-06-29 07:36 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        if ($sum) {
```suggestion
        if ($this->transofrmSum($sum) !== null) {
```

2021-06-29 07:36 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        $sum = $I->grabTextFrom("//div[@class='summary']//tbody//tr[$rowNumber]//td//span");
оце також зроби читабельніще пліз

2021-06-29 07:36 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +            return null;
перероби цей елсіф на ерлі ретурн стейтмент пліз

2021-06-29 07:53 UTC, Drakorgaur commented on tests/acceptance/seller/InternalTransferCest.php
> +            $billInfo['bill']['charges']['charge2'] = $billInfo['bill']['charges']['charge1'];
А что за айдишник мне нужен? Тип я создаю билл, который просто уравнивает баланс юзера, на котором проходит тест, до нуля(charge2, он опционален). Чтоб потом пополнить на 1000(charge1), и снять 1000 с трансфра.

2021-06-29 08:06 UTC, Drakorgaur commented on tests/acceptance/seller/InternalTransferCest.php
> +            $billInfo['bill']['charges']['charge2'] = $billInfo['bill']['charges']['charge1'];
![image](https://user-images.githubusercontent.com/83531949/123760988-0abbb800-d8ca-11eb-94f5-04a4bede4561.png)

2021-06-29 08:06 UTC, Drakorgaur commented on tests/acceptance/seller/InternalTransferCest.php
> +            $billInfo['bill']['charges']['charge2'] = $billInfo['bill']['charges']['charge1'];
зачем мне какие-то айдишники?

2021-06-29 08:34 UTC, Drakorgaur commented on tests/acceptance/seller/InternalTransferCest.php
> +        if ($sum) {
мне потом сумма нужна преобразованная. тип $sum до transformSum = -$12,400.50 (не пройдет для билла), а после трансформа -12400.50,
так что я не могу убрать строку $sum = $this->transofrmSum($sum);

2021-06-30 07:15 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        if (similar_text($currentBalance, '-')) {
треба навпаки в іф писать те, що має сразу вийти з функції (нулл), а інше писать після, щоб основна ідея метода не була в скоупі іфа і відідвинута табом

2021-06-30 07:25 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        if ($sum !== null) {
і отут ще

2021-06-30 07:27 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        if (!similar_text($currentBalance, '-')) {
кстаті я думаю краще перевірять по підстрокі завжди через `strstr` або `strpos`

2021-06-30 08:04 UTC, strorch requested changes

2021-06-30 08:04 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +            $sum = (int)$sum;
втф ?)

2021-06-30 08:04 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        if ($sum == null) {
```suggestion
        if ($sum === null) {
```
завжди зрівнюй чітко

2021-06-30 08:04 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +            $billInfo['bill']['charges']['charge2']['type'] = 'PayPal';
так стоп, оце має буть в дата провайдері, ти тут копіюєш чардж1, можеш зробить це в ньому просто, а в тесті мінять суму

2021-06-30 08:06 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +            $sum = (int)$sum;
ше й з*їхало усе

2021-06-30 08:09 UTC, Drakorgaur commented on tests/acceptance/seller/InternalTransferCest.php
> +            $sum = (int)$sum;
string $sum  - 12454,53
int      $sum  - 12454
т.к. метод в bill/Create getChargesTotalSum берет только integer, то мне нельзя вписывать в charge 12454.53, иначе в сумме билла будет на 53 цента меньше чем у чарджей

2021-06-30 08:50 UTC, strorch approved these changes

2021-06-30 08:52 UTC, strorch requested changes

2021-06-30 08:52 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        $sum = (int)$sum;
так хай трансформ сум вертає просто інт і там роби каст

2021-06-30 08:52 UTC, strorch commented on tests/acceptance/seller/InternalTransferCest.php
> +        $billInfo['bill']['charges']['charge1']['sum'] += ++$sum;
у тебе перед правками в тесті був `charge2`  а чо він пропав?

2021-06-30 12:29 UTC, Drakorgaur commented on tests/acceptance/seller/InternalTransferCest.php
> +        $billInfo['bill']['charges']['charge1']['sum'] += ++$sum;
я че-т запутался в твоих мыслях. Я подумал, что ты хочешь чтоб я в первом чардже просто сумму сменил. И вместо двух чарджей на $1000 и на $x, я сделал один на сумму $(x+1000).
И я вот в последнем коммите убрал чарджы вообще теперь там лишь билл(и билл принимает значение $(x+1000). 
Для наглядности логики теста - лучше делать с двумя чарджами.
Для эффективности кода - один билл. 
Что лучше? 
![image](https://user-images.githubusercontent.com/83531949/123958032-3e274100-d9b5-11eb-8afb-31ab4d37e51e.png)

2021-07-01 10:42 UTC, strorch approved these changes

2021-07-01 10:43 UTC, merged