New Test added
hiqdev/hipanel-module-finance pull request #271
Opened 2021-07-02 12:58 UTC by Drakorgaur

Тест проверяет общий фильтр для биллов. 
Есть раздел типов Domain Services и он в ключает в себя Delete by AGP и  Registration. При поиске по фильтру Domain Services, должны быть видны биллы и с типом Registration и с Delete...

2021-07-06 07:22 UTC, strorch requested changes

2021-07-06 07:22 UTC, strorch commented on tests/acceptance/manager/PaymentsFilterCest.php
> +    public function createBillsWithDifferentTypes(Manager $I, Example $example): void
оцей тест не потрібен, вже є тести які створюють біл. якщо тобі треба перевірить створення з різними типами то додай ще один масів біла в провайдер тих тестів

2021-07-06 07:22 UTC, strorch commented on tests/acceptance/manager/PaymentsFilterCest.php
> +        foreach ($dataBill as $bill) {
і оцей цикл має виконать сам провайдер, який для кожного елемента масіва виконає цей тест

2021-07-06 07:22 UTC, strorch commented on tests/acceptance/manager/PaymentsFilterCest.php
> +    public function ensureTypeFilterWorksCorrectly(Manager $I, Example $example): void
і цей тест можеш засунуть в тест клас де створюються біли, шоб їх по 100 раз не створювать

2021-07-09 08:09 UTC, strorch requested changes

2021-07-09 08:09 UTC, strorch commented on tests/acceptance/seller/BillCreationCest.php
> +        $this->billdata = $this->getBillData();
це має буть в дата провайдері

2021-07-09 08:09 UTC, strorch commented on tests/acceptance/seller/BillCreationCest.php
> +        $this->index = new Index($I);
кстаті я хз як правильніше буде, тому що _before спрацює для кожного теста в класі, але по факту не кожному тесту треба ці 2 сторінки

2021-07-09 08:09 UTC, strorch commented on tests/acceptance/seller/BillCreationCest.php
>          $updatePage = new Update($I);
вот апдейт ти ж не виніс в _before

2021-07-09 08:09 UTC, strorch commented on tests/acceptance/seller/BillCreationCest.php
> +            'bill1' => [
ключі біл1б біл2 писать не обов?язково

2021-07-09 08:09 UTC, strorch commented on tests/acceptance/seller/BillCreationCest.php
> +        $this->create->fillMainBillFields($this->billdata['bill1']);
не правильно все працює, для кожного біла треба все перевірять

2021-07-09 08:34 UTC, Drakorgaur commented on tests/acceptance/seller/BillCreationCest.php
> +        $this->billdata = $this->getBillData();
я пробовал _before ж принимает второй аргумент, он жеж _before($test). И Example $example оне не принимает.

2021-07-09 08:39 UTC, Drakorgaur commented on tests/acceptance/seller/BillCreationCest.php
> +        $this->index = new Index($I);
Я вынесу пока  в _before, если скажешь переделать - переделаю

2021-07-09 09:01 UTC, Drakorgaur commented
https://github.com/hiqdev/hipanel-core/pull/189

2021-07-14 06:57 UTC, strorch requested changes

2021-07-14 06:57 UTC, strorch commented on tests/_support/Page/bill/Index.php
> +            unset($this->billdata[$bill]['quantity']);
$this->billdata шо це, такої проперті немає в цьому класі

2021-07-14 06:57 UTC, strorch commented on tests/_support/Page/bill/Index.php
> +        foreach ($bills as $bill) {
ну думаю що потрібно перевірять масів білов, у тебе тест запускається для кожного біла окремо, перевіряй для одного

2021-07-14 06:57 UTC, strorch commented on tests/acceptance/seller/BillCreationCest.php
> +            'sum'       => -350,
так хай і далі не проходить якшо це баг

2021-07-14 07:18 UTC, Drakorgaur commented on tests/acceptance/seller/BillCreationCest.php
> +            'sum'       => -350,
проблема в том, что я не могу его руками проверить. :/

2021-07-15 14:33 UTC, merged