Fix import paymants from paysystems
hiqdev/hipanel-module-finance pull request #274
Opened 2021-07-08 11:57 UTC by bladeroot

2021-07-08 12:33 UTC, tafid approved these changes

2021-07-09 08:22 UTC, strorch requested changes

2021-07-09 08:22 UTC, strorch commented on src/forms/BillImportFromFileForm.php
> +        return Yii::$app->cache->getOrSet([__CLASS__, __METHOD__, $this->requisite_id], function() {
а чого модель форми має робить запрос в базу?

2021-07-09 08:22 UTC, strorch commented on src/forms/BillImportFromFileForm.php
> +    public function guessRequisiteType(): string
може цей функціонал краще хай робить апі? бо до цієї логіки важко докопатись, ще й вона в формі лежить

2021-07-09 08:22 UTC, strorch commented on src/forms/BillImportFromFileForm.php
> +    public function getClientSubstrings(): ?array
а нашо нул, можна ж просто пустий масів вертать. через то шо тут нул далі по коду куча перевірок на нул, це все костилі

2021-07-09 08:22 UTC, strorch commented on src/helpers/parser/parsers/AbstractParser.php
> +    public function findClient(string $str): ?string
назва функції не співпадає з тим що вона робить

2021-07-09 08:22 UTC, strorch commented on src/helpers/parser/parsers/PaxumParser.php
> +            );
жесть)

2021-07-09 08:22 UTC, strorch commented on src/menus/SidebarMenu.php
> +                        'visible' => $user->can('plan.read') && (Yii::$app->params['module.finance.plan.required.additional.rights'] ? $user->can('support') : true),
супорт може замінить на шось?

2021-07-09 18:50 UTC, bladeroot commented on src/menus/SidebarMenu.php
> +                        'visible' => $user->can('plan.read') && (Yii::$app->params['module.finance.plan.required.additional.rights'] ? $user->can('support') : true),
Не хочу. Я це не правив

2021-07-09 19:08 UTC, bladeroot commented on src/forms/BillImportFromFileForm.php
> +    public function guessRequisiteType(): string
Вона і раніше лежала, просто була прибита цвяхами.

2021-07-09 20:07 UTC, bladeroot commented on src/forms/BillImportFromFileForm.php
> +    public function getClientSubstrings(): ?array
Тому що перевірка "далі по коду" лише одна. І вона потрібна. Нема масиву - нема опрацювання форми.

2021-07-09 20:10 UTC, bladeroot commented on src/helpers/parser/parsers/AbstractParser.php
> +    public function findClient(string $str): ?string
Точно? Запропонуй свою назву. А що воно робить? Як мінімум намагається в рядку знайти логін. А в getClient описуэться з якого рядка. Напевн це теж криво.

2021-07-09 20:10 UTC, bladeroot commented on src/helpers/parser/parsers/PaxumParser.php
> +            );
Пропоную запитать у Paxum, якого дыдька така жесть

2021-07-12 07:32 UTC, strorch requested changes

2021-07-12 07:32 UTC, strorch commented on src/helpers/parser/parsers/PaxumParser.php
> +            );
тут просто таби не по psr

2021-07-12 07:32 UTC, strorch commented on src/helpers/parser/parsers/AbstractParser.php
> +    public function findClient(string $str): ?string
findClient асоціюється з пошуком екземплярів класа Client з бази, а цьому методу підходить matchClientsFromSubtrings

2021-07-12 07:32 UTC, strorch commented on src/helpers/parser/parsers/PaxumParser.php
> +        return $this->getSum() + $this->getFee();
ну жесть йопта виходить null + float може буть???

2021-07-12 07:32 UTC, strorch commented on src/menus/SidebarMenu.php
> +                        'visible' => $user->can('plan.read') && (Yii::$app->params['module.finance.plan.required.additional.rights'] ? $user->can('support') : true),
всмислі не хочу, ми ж домовились шо виправляєм по мірі торкання коду

2021-07-12 07:32 UTC, strorch commented on src/helpers/parser/parsers/AbstractParser.php
> +    public function __construct(UploadedFile $file, BillsImporter $importer)
а це не поламає всі інші парсери?

2021-07-12 07:32 UTC, strorch commented on src/helpers/parser/parsers/PayPalParser.php
> +    protected function replaceComma(?string $str): ?float
```
php > echo gettype((float)null);
double
```

вся ця робота з нулами що тут є це ужас страшний

2021-07-12 07:33 UTC, strorch commented on src/forms/BillImportFromFileForm.php
> +    public function getClientSubstrings(): ?array
рефактор на то і рефактор

2021-07-14 10:31 UTC, bladeroot commented on src/helpers/parser/parsers/AbstractParser.php
> +    public function __construct(UploadedFile $file, BillsImporter $importer)
Ні, не поламає. Тому що "інші" - це один чи два. І там зміни теж зроблені.

2021-07-14 10:33 UTC, bladeroot commented on src/menus/SidebarMenu.php
> +                        'visible' => $user->can('plan.read') && (Yii::$app->params['module.finance.plan.required.additional.rights'] ? $user->can('support') : true),
Ну взагалі то це ще ти мав виправити. Коли розрулював парти. У мене зараз мозок не дуже хоче винаходити нові правила і закопуватись ще глибше

2021-07-14 11:12 UTC, hiqsol requested changes

2021-07-14 11:12 UTC, hiqsol commented on src/menus/SidebarMenu.php
> +                        'visible' => $user->can('plan.read') && (Yii::$app->params['module.finance.plan.required.additional.rights'] ? $user->can('support') : true),
Юра, нечего тут торговаться: трогаешь код, видишь can(support) меняешь на can(access-subclients)

2021-07-14 11:12 UTC, hiqsol commented on src/menus/SidebarMenu.php
> +                        'visible' => $user->can('plan.read') && (Yii::$app->params['module.finance.plan.required.additional.rights'] ? $user->can('support') : true),
```suggestion
                        'visible' => $user->can('plan.read') && (Yii::$app->params['module.finance.plan.required.additional.rights'] ? $user->can('access-subclients') : true),
```

2021-07-14 11:12 UTC, hiqsol commented on src/helpers/parser/parsers/AbstractParser.php
> +    public function findClient(string $str): ?string
```suggestion
    public function extractClient(string $str): ?string 
```

2021-07-14 11:12 UTC, hiqsol commented on src/helpers/parser/parsers/PaxumParser.php
> +            );
тут поправь по PSR, давно договорились форматить не по вкусу, а по PSR

2021-07-14 11:12 UTC, hiqsol commented on src/helpers/parser/parsers/PaxumParser.php
> +        return $this->getSum() + $this->getFee();
Юра делал на реальных данных, сейчас это трогать - заново тестить.
По хорошему надо делать тесты и рефакторить, но пока хер с ним, не критично.

2021-07-14 11:49 UTC, hiqsol commented on src/forms/BillImportFromFileForm.php
> +    public function getClientSubstrings(): ?array
от того что ты там заменишь проверку на нул на empty - хуже не станет
всё равно пустой массив client substrings тоже не юзабельный

2021-07-14 11:55 UTC, hiqsol commented on src/forms/BillImportFromFileForm.php
> +    public function guessRequisiteType(): string
у нас развитый АПИ. То что какой-то нетривиальный функционал можно сделать не дописывая АПИ - это хорошо, а не плохо.  И так и надо делать по возможности.

а вот всю работу с АПИ - да, надо чуть подвинуть в другой слой

2021-07-14 12:04 UTC, hiqsol commented on src/forms/BillImportFromFileForm.php
> +        return Yii::$app->cache->getOrSet([__CLASS__, __METHOD__, $this->requisite_id], function() {
да, Юра, подвинь, а то напихал лишнее в форму

перенеси в importer работу с API, и `getImportData`
а Importer прокинь в форму di'ем

и потом у тебя будет

2021-07-19 07:55 UTC, strorch approved these changes

2021-07-19 13:03 UTC, hiqsol reviewed
ладно хай буде так

2021-07-19 13:03 UTC, merged