Import payments Test
hiqdev/hipanel-module-finance pull request #277
Opened 2021-07-13 08:57 UTC by Drakorgaur

https://github.com/hiqdev/hipanel-core/pull/191

2021-07-14 07:34 UTC, strorch requested changes

2021-07-14 07:34 UTC, strorch commented on tests/_support/Page/import/Create.php
> +            }
таби поїхали, вистав в едіторі щоб відображались не таби а тільки пробіли

2021-07-14 07:34 UTC, strorch commented on tests/_support/Page/import/Create.php
> +        $importString = substr_replace($importString, '', 0, 1);
якщо $importData буде пустою, то буде виклик substr_replace(null, ...

2021-07-14 07:34 UTC, strorch commented on tests/acceptance/manager/ImportPaymentsCest.php
> +        $view->viewBillById($this->billId);
у тебе цей метод спрацьовує не як окремий тест, тобі проперті білл_ід не треба, можеш просто передать в параметр до метода

2021-07-14 07:34 UTC, strorch commented on tests/_support/Page/bill/View.php
> +        $this->gridView->containsBillDataInTable($billData);
жду рефактора

2021-07-14 07:49 UTC, Drakorgaur commented on tests/_support/Page/import/Create.php
> +        $importString = substr_replace($importString, '', 0, 1);
А зачем мне в метод засовывать пустой массив importData?

2021-07-15 06:25 UTC, Drakorgaur commented on tests/_support/Page/import/Create.php
> +        $importString = substr_replace($importString, '', 0, 1);
я кажись понял, что ты имел ввиду. Смотри в foreach у меня массив превращается в строку, где каждый элемент отделяется ` ; ` , и из-за того, что изначально importString я объявил как пустую, то substr_replace убирает первый символ.

2021-07-15 14:34 UTC, strorch commented on tests/_support/Page/import/Create.php
> +        $importString = substr_replace($importString, '', 0, 1);
я бачу нашо ти це зробив, але я твою функцію поламаю якшо в моєму тесті $importDatа = []

2021-07-19 08:13 UTC, strorch requested changes

2021-07-19 08:13 UTC, strorch commented on tests/_support/Page/import/Create.php
> +            $importString = $importString . ';' . $element;
кстаті почитай про функції в пхп implode, explode та інші і перепеши без цього цикла пліз

2021-07-19 08:13 UTC, strorch commented on tests/acceptance/manager/ImportPaymentsCest.php
> +        $this->checkThatBillWasCreatedCorrectly($I, $importData, $billId);
в цьому методі у тебе перемішались виклики з this, importCreate, billCreate.
зроби пліз так шоб все було послідовно. я думаю тут можна this-> перенести в один з цих класів

2021-07-19 08:13 UTC, strorch commented on tests/acceptance/manager/ImportPaymentsCest.php
> +        $I->clickLink('Import from a file', '//ul');
це я думаю тоже можна перенести в ImportCreate і видаляться куча непотрібних private методів

2021-07-19 08:13 UTC, strorch commented on tests/acceptance/manager/ImportPaymentsCest.php
> +        $I->click("//div[@id = 'w1'] //button[@class = 'close']");
це тоже

2021-07-19 08:13 UTC, strorch commented on tests/acceptance/manager/ImportPaymentsCest.php
> +        $I->see('Client;Time;Amount;Currency;Type;Description;Requisite', 'pre');
і це

2021-07-20 07:53 UTC, Drakorgaur commented on tests/acceptance/manager/ImportPaymentsCest.php
> +        $I->clickLink('Import from a file', '//ul');
Ну прикол в том, что в это время тест на странице bill/index. и там проверяет работоспособность линков. Это не на странице import/create

2021-07-20 08:05 UTC, strorch commented on tests/acceptance/manager/ImportPaymentsCest.php
> +        $I->clickLink('Import from a file', '//ul');
зроби $importPayments->visitFromFilePage() хз.. importPayments це ж не сторінка а клас який її описує, або можеш засунуть це в BillIndex тіпа бо ця лінка на цій сторінкі   $index->visitImportPage()

2021-07-20 08:07 UTC, strorch commented on tests/acceptance/manager/ImportPaymentsCest.php
> +    private function enureImportPaymentsWorksCorrectly(Manager $I, array $importData): void
короче цей метод не читаємий для тестів. я бачу шо його можна поділить на візіт, чек пейдж, імпорт і це все розкласти по класам

2021-07-20 08:08 UTC, strorch commented on tests/acceptance/manager/ImportPaymentsCest.php
> +    private function ensureICantCreateImportedBillWithouData(Manager $I): void
а цей метод також не потрібний і звучить наче окремий тест

2021-07-20 08:09 UTC, strorch commented on tests/acceptance/manager/ImportPaymentsCest.php
> +        $I->clickLink('Import from a file', '//ul');
вот бачиш то шо тут таке напесино і не зрозуміло що де клікається робить тест не читаємим

2021-07-21 08:05 UTC, Drakorgaur commented on tests/acceptance/manager/ImportPaymentsCest.php
> +    private function ensureICantCreateImportedBillWithouData(Manager $I): void
сделан отдельным тестом

2021-07-21 08:17 UTC, Drakorgaur commented on tests/acceptance/manager/ImportPaymentsCest.php
> +    private function enureImportPaymentsWorksCorrectly(Manager $I, array $importData): void
Вроде сейчас разложены, если нет - то объясни, соррян, не понимаю.

2021-08-05 07:51 UTC, strorch requested changes

2021-08-05 07:51 UTC, strorch commented on tests/acceptance/manager/ImportPaymentsCest.php
> +        $I->waitForElement("//h1[contains(text(),'Create payment')]", 10);
```suggestion
        $I->waitForText('Create payment');
```

попробуй так плз

2021-08-05 09:31 UTC, Drakorgaur commented on tests/acceptance/manager/ImportPaymentsCest.php
> +        $I->waitForElement("//h1[contains(text(),'Create payment')]", 10);
супир

2021-08-06 07:22 UTC, strorch approved these changes

2021-08-06 07:22 UTC, merged