Tariff plan tip update
hiqdev/hipanel-module-finance pull request #281
Opened 2021-07-16 07:16 UTC by Drakorgaur

2021-07-19 08:03 UTC, strorch commented on tests/_support/Page/price/Create.php
> +        $I->waitForElement('#create-prices');
ці 3 строки вже написані, не пиши 1 і той же код по 100 раз

2021-07-19 08:06 UTC, strorch requested changes

2021-07-19 08:06 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +                    'name'     => $this->templateName = 'template tariff' . uniqid(),
this->templateName ініціалізується тут, а використовується в цьому методі вище, хіба це працює?

2021-07-19 08:06 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +                    'name'     => $this->templateName = 'template tariff' . uniqid(),
не думаю що ім*я таріфа треба класти в проперті.
ідея проперті для айдішніка шоб 1 тест створив це айді а інший тест по айді щось перевірив.

2021-07-20 08:15 UTC, strorch commented on tests/acceptance/seller/TariffPlansTipCest.php
> +    protected $templateName;
я просив це прибрать

2021-08-05 07:47 UTC, strorch requested changes

2021-08-05 07:47 UTC, strorch commented on tests/_support/Entity/TemplateTariff.php
> +class TemplateTariff
цей клас не потрібен бо шо темплейт шо не темплейт - це таріфи, або якщо тобі треба відділить 2 таріфа і їх якось розрізнить, то можеш віднаслідувати цей клас від таріфа, і поля і методи збережуться

2021-08-05 07:47 UTC, strorch commented on tests/acceptance/seller/TariffPlansCest.php
> +                'this' => new Tariff(
```suggestion
                new Tariff(
```

2021-08-05 07:47 UTC, strorch commented on tests/acceptance/seller/TariffPlansCest.php
> +    private $tariff;
тайпхінт

2021-08-05 07:47 UTC, strorch commented on tests/acceptance/seller/TariffPlansCest.php
> +    private $tariff;
шось не то, треба тільки айдішку зберігать між тестами, увесь об*єкт треба з дата провайдера забирать

2021-08-05 07:47 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +    public function getTariffData(): array
в методах куча раз написано таріф, і так ясно шо це таріф) видали пліз

2021-08-05 07:47 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +        $this->data = $data;
зроби краще всі поля окремо і вертай значення цих полей, бо массів важко валідується і породжує костилі

2021-08-05 07:47 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +    private $name;
тайпхінт

2021-08-05 07:47 UTC, strorch commented on tests/acceptance/seller/TariffPlansCest.php
> +    private $tariff;
і в наступному тесті робить tariff->setId()

2021-08-07 08:44 UTC, Drakorgaur commented on tests/acceptance/seller/TariffPlansCest.php
> +    private $tariff;
Пишу для себя, чтоб не забыть, почему я не могу сделать сие. У меня ж в генераторе есть uniqid(). Так что я не могу вызывать датапровайдер больше раза -  имя темплейт тарифа. Варианты?

2021-08-07 08:45 UTC, Drakorgaur commented on tests/acceptance/seller/TariffPlansCest.php
> +                'this' => new Tariff(
Дата провайдер не принимает без 'this'. Я тебе по этому поводу писал. 
![image](https://user-images.githubusercontent.com/83531949/128594623-f4d509aa-1885-4da3-9028-b9f36e030ae7.png)

2021-08-07 08:45 UTC, Drakorgaur commented on tests/_support/Entity/TemplateTariff.php
> +class TemplateTariff
тут согласен

2021-08-07 08:49 UTC, Drakorgaur commented on tests/acceptance/seller/TariffPlansCest.php
> +    private $tariff;
При создании объекта тариф в генераторе. Первым создается класс ТемплейтТариф. Он принимает uniqid имя. И потом создается класс Тариф, в который в прайсы записывается имя ТемплейтТарифа.

2021-08-09 10:29 UTC, strorch requested changes

2021-08-09 10:29 UTC, strorch commented on tests/acceptance/seller/TariffPlansCest.php
> +                        'typeDropDownElements' => [],
а нашо ти робив це поле, якшо воно завжди пусте

2021-08-09 10:29 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +    public function getData(): array
якшо ти зробиш усі поля public, і зробиш $tariffArray = (array)$tariff; то буде те саме

2021-08-09 10:29 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +    public function __construct (array $data, TemplateTariff $template = null) {
якшо ти хочеш прописувать це в конструкторі, то прийнято кожне поле передавать окремим аргументом, або ти можеш зробить отак

```
public static function fromArray(array $tariffArray): self
{
    $self = new self();
    $self->name = $tariffArray['name'] ?? 'default';
    ...
    
    return $self;
}
```

але якшо ти робиш так, то теплейт таріф тоже треба передавать в масіві, і треба враховувать шо кожен елемент масіва може не існувать

2021-08-09 10:29 UTC, strorch commented on tests/acceptance/seller/TariffPlansCest.php
> +                $this->ensureICanCreateNewTariff($I, $tariff->template->getData())
таби поїхали

2021-08-09 10:29 UTC, strorch commented on tests/acceptance/seller/TariffPlansCest.php
> +        $tariff->setTemplateName($this->templateName);
досі не розумію нашо поле таріф нейм

2021-08-12 08:33 UTC, Drakorgaur commented on tests/acceptance/seller/TariffPlansCest.php
> +                        'typeDropDownElements' => [],
Его требует конструктор
![image](https://user-images.githubusercontent.com/83531949/129165222-82493629-8466-4911-8ab2-01ab88306cc4.png)

2021-08-13 08:05 UTC, Drakorgaur commented on tests/_support/Entity/Tariff.php
> +    public function getData(): array
![image](https://user-images.githubusercontent.com/83531949/129325163-842de2c1-cbcd-40ad-99ca-bac33c27089c.png)

2021-08-13 09:02 UTC, Drakorgaur commented on tests/_support/Entity/Tariff.php
> +    public static function fromArray(array $tariffArray, Tariff $tariff): void
Я надеюсь, яхоть от части сделал то, что ты просил. И тут соблюдается чисто формальность кода. Запихнул шаблон-Тариф в массив.

2021-08-13 09:03 UTC, Drakorgaur commented on tests/_support/Entity/Tariff.php
> +        $tariff->price = $tariffArray['price'] ?? [];
И еще я тут просто подумл, что если надо будет в будущем создавать тарифы. То для простоты, можно будет задавать лишь часть значений, которые нужны. А остальные будут дефолтными. 
Норм или убрать?

2021-08-16 09:31 UTC, strorch requested changes

2021-08-16 09:31 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +    {
$
```suggestion
    {
     $tariff = new self();
```

2021-08-16 09:31 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +    public static function fromArray(array $tariffArray, Tariff $tariff): void
$tariff = Tariff::fromArray($array);

2021-08-16 09:31 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +    public function __construct (array $data)
```suggestion
    public function __construct (string id, string name ....)
```

2021-08-16 09:31 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +        $tariff->type = $tariffArray['type'] ?? 'server';
```suggestion
        public const DEFAULT_TYPE = 'server';
        $tariff->type = $tariffArray['type'] ?? self::DEFAULT_TYPE;
```

2021-08-16 09:31 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +        $tariff->price = $tariffArray['price'] ?? [];
da

2021-08-16 09:31 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +    public TemplateTariff $template;
```suggestion
    public ?TemplateTariff $template = null;
```

2021-08-16 09:31 UTC, strorch commented on tests/_support/Entity/Tariff.php
> +<?php
```suggestion
<?php
declare(strict_types=1);
```

2021-08-16 09:31 UTC, strorch commented on tests/_support/Entity/TemplateTariff.php
> +<?php
```suggestion
<?php
declare(strict_types=1);
```

2021-08-16 09:31 UTC, strorch commented on tests/acceptance/seller/TariffPlansCest.php
> +<?php
```suggestion
<?php
declare(strict_types=1);
```

2021-08-18 07:09 UTC, Drakorgaur commented on tests/_support/Page/plan/Plan.php
>  }
я вот тут вот возможно сильно затупил. И аналог созданного Entity/Tariff этот файлик.

2021-08-19 09:48 UTC, strorch approved these changes

2021-08-19 09:48 UTC, merged