Sales action
hiqdev/hipanel-module-finance pull request #295
Opened 2021-09-02 06:45 UTC by Drakorgaur

2021-09-07 09:03 UTC, strorch requested changes

2021-09-09 06:35 UTC, Drakorgaur commented on tests/acceptance/seller/SalesCest.php
> +        $indexPage = new IndexPage($I);
IndexPage -  hipanel-core
Index - ...finance/tests/support/sale/Index.php

2021-09-09 08:22 UTC, strorch commented on tests/acceptance/seller/SalesCest.php
> +        #$column = $index->gridView->getColumnNumber('DC');
```suggestion
```

2021-09-09 08:23 UTC, strorch commented on tests/acceptance/seller/SalesCest.php
> +        $row[] = $index->getRowNumberInColumnByValue('DC', 'TEST-DS-02');
оці дані мають буть з датапровайдера

2021-09-09 08:24 UTC, strorch commented on tests/acceptance/seller/SalesCest.php
> +        foreach ($row as $currentRow) {
якшо з датапровайдером то можна обійтись без цього цикла

2021-09-09 08:24 UTC, strorch commented on tests/acceptance/seller/SalesIndexPageCest.php
> +    private $index;
```suggestion
    private IndexPage $index;
```

2021-09-09 08:25 UTC, strorch commented on tests/acceptance/seller/SalesCest.php
> +                'client' => 'testuser60798ee837548@test1.test1',
такого юзера по дефолту в базі немає

2021-09-09 08:26 UTC, strorch commented on tests/acceptance/seller/SalesCest.php
> +        $I->checkOption("//tbody/tr[2]//input[1]");
а є спосіб більш читаємий xpath написать?

2021-09-09 08:26 UTC, strorch commented on tests/acceptance/seller/SalesCest.php
> +        $saleData = $I->grabMultiple("//tbody/tr[1]");
не читаємо

2021-09-09 08:27 UTC, strorch commented on tests/acceptance/seller/SalesCest.php
> +        $I->click("//tbody/tr[1]/td[$column]//a");
не читаємо

2021-09-09 08:27 UTC, strorch commented on tests/acceptance/seller/SalesCest.php
> +        $I->checkOption("//tbody/tr[2]//input[1]");
не читаємо

2021-09-09 08:27 UTC, strorch commented on tests/acceptance/seller/SalesCest.php
> +            $I->waitForElementVisible("//div[contains(text(),'Affected items')]", 90);
```suggestion
            $I->waitForText('Affected items');
```

2021-09-09 09:02 UTC, Drakorgaur commented on tests/acceptance/seller/SalesCest.php
> +        $row[] = $index->getRowNumberInColumnByValue('DC', 'TEST-DS-02');
мне с дата провайдера взять номера строк? тип строка 3 и 5? это странно, нет?

2021-09-14 07:30 UTC, strorch requested changes

2021-09-14 07:30 UTC, strorch commented on tests/acceptance/SalesCest.php
> +            ]
```suggestion
            ],
```

2021-09-14 07:30 UTC, strorch commented on tests/acceptance/SalesCest.php
> +        }
```suggestion
        foreach ([1, 2] as $rowId) {
            $I->checkOption(sprintf("//input[@value='%s']", $index->getRowIdByNumber($rowId)));
        }
```

2021-09-14 07:30 UTC, strorch commented on tests/acceptance/SalesCest.php
> +
```suggestion
```

2021-09-14 07:30 UTC, strorch commented on tests/acceptance/SalesCest.php
> +    public function ensureICanEditSeveralSales(Seller $I, Example $example): void
половина кода з метода ensureICanDeleteSeveralSales повторюється тут, винеси це в спільний метод

2021-09-28 08:55 UTC, strorch approved these changes

2021-09-28 08:55 UTC, strorch commented on tests/acceptance/SalesCest.php
> +        $I->needPage('/server/server');
```suggestion
        $I->needPage(Url::to('@server/index'));
```

2021-09-28 08:56 UTC, merged