[manager] BillBulkButtonActionCest Test reworked
hiqdev/hipanel-module-finance pull request #302
Opened 2021-09-28 10:56 UTC by Drakorgaur

2021-09-29 09:38 UTC, strorch requested changes

2021-09-29 09:38 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +    public function fillBillDescriptionField(string $descr, int $billNo = 0): void
```suggestion
    public function fillBillDescriptionField(int $billNumber, string $descr): void
```
не може буть не обов*язковим номер біла якому ти вписуєш дескріпшн, це з назви метода не логічно

2021-09-29 09:38 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +        (new Input($I, "#billform-$billNo-label"))->setValue($descr);
```suggestion
        (new Input($this->tester, "#billform-$billNo-label"))->setValue($descr);
```

2021-09-29 09:38 UTC, strorch commented on tests/acceptance/manager/BillBulkButtonCest.php
> +    }
```suggestion
         $I->checkOption("//tbody//tr[0]//input");
         $I->checkOption("//tbody//tr[1]//input");
```
забагато кода, щоб перевірить 2 опшна

2021-09-29 09:38 UTC, strorch commented on tests/acceptance/manager/BillBulkButtonCest.php
> +                'method' => 'ensureUpdateAndCopyBulkButtonsWorkCorrectly',
оперувать назвами методів - це таке собі, ще й не по ооп. ти оперуєш для абстракції і назвою екшна і його методом. якщо хочеш так то краще зроби одним. наприклад:

```
interface Ensurable
{
 public function ensure(AcceptanceTester $I);
}

class EnsureUpdate implements Ensurable
{
   ...
}
class EnsureCopy implements Ensurable
{
   ...
}
class EnsureDelete implements Ensurable
{
   ...
}


class Test
{
   /** @dataProvider provider */
   public function testMethod(Manager $I, $data)
   {
       $ensureObject = \Yii::createObject($data['class']);
       $ensureObject->ensure($I);
   }

   public function provider()
   {
     return [
        [
             'class' => EnsureDelete::class,
         ],
        [
             'class' => EnsureCopy::class,
        ],
   }
}
```

АБО 

можеш просто руками виписать це в 3 окремих теста, бо дата провайдер предназначений для тестових данних а не абстрагування кода теста, і так навіть буде читабельніше і простіше

2021-09-29 09:38 UTC, strorch commented on tests/acceptance/manager/BillBulkButtonCest.php
> +    protected function BillDataProvider(): array
```suggestion
    protected function billDataProvider(): array
```

2021-09-29 09:44 UTC, Drakorgaur commented on tests/_support/Page/bill/Create.php
> +    public function fillBillDescriptionField(string $descr, int $billNo = 0): void
Ну тип если создается/апдейтится/копируется билл, то там одно поле - #billform-0-label, зачем тогда задавать руками?. 
ну а если правятся два - то там #billform-0-label #billform-1-label и тп. И там уже над их различать.

2021-09-29 09:46 UTC, Drakorgaur commented on tests/_support/Page/bill/Create.php
> +    public function fillBillDescriptionField(string $descr, int $billNo = 0): void
это не номер самого била, а его место на страничке правки
![image](https://user-images.githubusercontent.com/83531949/135244952-f6b8fa22-3c2c-4aa9-9a8f-11164da59d20.png)

2021-09-29 10:02 UTC, strorch commented on tests/_support/Page/bill/Create.php
> +    public function fillBillDescriptionField(string $descr, int $billNo = 0): void
у тебе цей метод лежить в класі креейт, він не знає скільки ти хочеш білів створювать. типу якщо метод заповнює всі біли, то він прийме всі біли, якщо метод заповнює поля по одному білу то він прийме поля по одному білу, а якщо ти хочеш метод який заповнює поле для конкретного біла, то треба і то і то поле задавать

2021-10-04 09:09 UTC, strorch approved these changes

2021-10-04 09:10 UTC, merged