HP-1505 Add filters to Payments (Bills)
hiqdev/hipanel-module-finance pull request #452
Opened 2023-08-10 15:22 UTC by gadezist

2023-08-14 10:41 UTC, hiqsol approved these changes

2023-08-14 10:59 UTC, SilverFire requested changes
https://github.com/hiqdev/hipanel-module-server/pull/215/files

Add similar change

2023-08-14 11:23 UTC, SilverFire requested changes

2023-08-14 11:23 UTC, SilverFire commented on src/models/Bill.php
> +class Bill extends \hipanel\base\Model implements HasSumAndCurrencyAttributesInterface, TaggableInterface
```suggestion
class Bill extends \hipanel\base\Model implements HasSumAndCurrencyAttributesInterface
```

2023-08-14 11:23 UTC, SilverFire commented on src/models/Bill.php
> +            ],
```suggestion
```

2023-08-14 11:23 UTC, SilverFire commented on src/models/BillSearch.php
> +            'tags',
```suggestion
            'client_tags',
```

2023-08-14 11:23 UTC, SilverFire commented on src/models/BillSearch.php
> +            'tags' => Yii::t('hipanel:finance', 'Client tags'),
```suggestion
            'client_tags' => Yii::t('hipanel:finance', 'Client tags'),
```

2023-08-14 11:23 UTC, SilverFire commented on src/views/bill/_search.php
> +      <?= $search->field('tags')->widget(TagsInput::class) ?>
```suggestion
      <?= $search->field('client_tags')->widget(TagsInput::class) ?>
```

2023-08-14 11:23 UTC, SilverFire commented on src/views/bill/_search.php
> +      <?= $search->field('tags')->widget(TagsInput::class) ?>
Widget should be properly configured to search for Client tags

2023-08-15 13:32 UTC, gadezist commented on src/models/Bill.php
> +            ],
Тут викликається метод fetchTags() для отримання тегів

2023-08-15 13:34 UTC, gadezist commented on src/views/bill/_search.php
> +      <?= $search->field('tags')->widget(TagsInput::class) ?>
Тут вже закладена логіка на контроллер і екшн який я создав в апі. Що ти маєш на увазі я не дуже зрозумів?

2023-08-17 09:06 UTC, SilverFire requested changes

2023-08-17 09:06 UTC, SilverFire commented on src/models/Bill.php
> +            ],
У білів немає тегів. Тобі треба використовувати теги клієнтів

2023-08-17 09:06 UTC, SilverFire commented on src/views/bill/_search.php
> +      <?= $search->field('client_tags')->widget(TagsInput::class) ?>
Який запит воно робить для `getAvailableTags()` при такому виклику?

2023-08-22 14:01 UTC, SilverFire commented on src/models/Bill.php
> +            ],
Що тут?

2023-08-22 14:02 UTC, SilverFire commented on src/models/Bill.php
> +    }
Ця реалізація є в моделі Client
Тобі треба з віджета робити запит до клієнтів, а не до білів!

2023-08-22 14:02 UTC, SilverFire commented on src/views/bill/_search.php
> +      <?= $search->field('client_tags')->widget(TagsInput::class) ?>
??

2023-08-22 14:04 UTC, SilverFire commented on src/views/bill/_search.php
> +      <?= $search->field('tags')->widget(TagsInput::class) ?>
Тобі треба зробити, щоб `TagsInput` приймав параметр типу такого, щоб він для запиту списку тегів використовував не поточну модель `$search`, яка `instanceof BillsSearch`, а щоб воно ходило до клієнтів. Типу такого:

```php
      <?= $search->field('tags')->widget([
         'class' => TagsInput::class,
         'targetClass' => ClientSearch::class
      ]) ?>

```

2023-08-23 09:49 UTC, SilverFire approved these changes

2023-08-23 09:50 UTC, merged

2023-08-23 10:00 UTC, gadezist commented on src/models/Bill.php
> +            ],
Поправив, видалив

2023-08-23 10:01 UTC, gadezist commented on src/views/bill/_search.php
> +      <?= $search->field('tags')->widget(TagsInput::class) ?>
+

2023-08-23 10:03 UTC, gadezist commented on src/views/bill/_search.php
> +      <?= $search->field('client_tags')->widget(TagsInput::class) ?>
Був запит fetchTags моделі що використовується, це поправив, тепер можна передать будь яку модель для getAvailableTags()

2023-08-23 10:03 UTC, gadezist commented on src/models/Bill.php
> +    }
Поправив